<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['name' => 'India'],
            ['name' => 'United States'],
            ['name' => 'Canada'],
            ['name' => 'Australia'],
            ['name' => 'Brazil'],
            ['name' => 'United Kingdom'],
            ['name' => 'France'],
            ['name' => 'Germany'],
            ['name' => 'Japan'],
            ['name' => 'China'],
            ['name' => 'Russia'],
            ['name' => 'South Africa'],
            ['name' => 'Mexico'],
            ['name' => 'Argentina'],
            ['name' => 'Italy'],
            ['name' => 'Spain'],
            ['name' => 'South Korea'],
            ['name' => 'New Zealand'],
            ['name' => 'Pakistan'],
            ['name' => 'Bangladesh'],
            ['name' => 'Nepal'],
            ['name' => 'Sri Lanka'],
            ['name' => 'Indonesia'],
            ['name' => 'Malaysia'],
            ['name' => 'Thailand'],
            ['name' => 'Vietnam'],
            ['name' => 'Philippines'],
            ['name' => 'Singapore'],
            ['name' => 'Turkey'],
            ['name' => 'Saudi Arabia'],
            ['name' => 'United Arab Emirates'],
            ['name' => 'Egypt'],
            ['name' => 'Nigeria'],
            ['name' => 'Kenya'],
            ['name' => 'Ghana'],
            ['name' => 'Morocco'],
            ['name' => 'Algeria'],
            ['name' => 'Tanzania'],
            ['name' => 'Uganda'],
            ['name' => 'Zimbabwe'],
            ['name' => 'Ethiopia'],
            ['name' => 'Sudan'],
            ['name' => 'Iraq'],
            ['name' => 'Syria'],
            ['name' => 'Jordan'],
            ['name' => 'Lebanon'],
            ['name' => 'Israel'],
            ['name' => 'Palestine'],
            ['name' => 'Qatar'],
            ['name' => 'Kuwait'],
            ['name' => 'Oman'],
            ['name' => 'Yemen'],
            ['name' => 'Afghanistan'],
            ['name' => 'Iran'],
            ['name' => 'Iceland'],
            ['name' => 'Norway'],
            ['name' => 'Sweden'],
            ['name' => 'Finland'],
            ['name' => 'Denmark'],
            ['name' => 'Netherlands'],
            ['name' => 'Belgium'],
            ['name' => 'Luxembourg'],
            ['name' => 'Switzerland'],
            ['name' => 'Austria'],
            ['name' => 'Portugal'],
            ['name' => 'Greece'],
            ['name' => 'Poland'],
            ['name' => 'Czech Republic'],
            ['name' => 'Hungary'],
            ['name' => 'Slovakia'],
            ['name' => 'Romania'],
            ['name' => 'Bulgaria'],
            ['name' => 'Ukraine'],
            ['name' => 'Belarus'],
            ['name' => 'Croatia'],
            ['name' => 'Serbia'],
            ['name' => 'Bosnia and Herzegovina'],
            ['name' => 'Slovenia'],
            ['name' => 'North Macedonia'],
            ['name' => 'Albania'],
            ['name' => 'Montenegro'],
            ['name' => 'Kosovo'],
            ['name' => 'Estonia'],
            ['name' => 'Latvia'],
            ['name' => 'Lithuania'],
            ['name' => 'Georgia'],
            ['name' => 'Armenia'],
            ['name' => 'Azerbaijan'],
            ['name' => 'Kazakhstan'],
            ['name' => 'Uzbekistan'],
            ['name' => 'Turkmenistan'],
            ['name' => 'Kyrgyzstan'],
            ['name' => 'Tajikistan'],
            ['name' => 'Mongolia'],
            ['name' => 'Myanmar'],
            ['name' => 'Cambodia'],
            ['name' => 'Laos'],
            ['name' => 'Brunei'],
            ['name' => 'East Timor'],
            ['name' => 'Maldives'],
        ]);
        
    }
}
